version: '3'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: pillowdb3
    networks:
      - BRIDGE
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  
  nestjs:
    image: nest-service3
    container_name: nest-container3
    networks:
      - BRIDGE
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

  servicedotnet:
    image: rest-service3
    container_name: rest-container3
    networks:
      - BRIDGE
    ports:
      - "5181:8080"
    depends_on:
      - nestjs

networks:
  BRIDGE:
    driver: bridge

